### ISSUE TITLE
Potential out-of-bounds access in s1323

### ISSUE THREAD

**Issue by doudou** [SINTEF-Geometry/SISL#27]
GCC 8.3 warns that

~~~
warning: iteration 3 invokes undefined behavior [-Waggressive-loop-optimizations]
~~~

[here `s1323.c:205:12:`](https://github.com/SINTEF-Geometry/SISL/blob/master/src/s1323.c#L205)

Indeed, its seems that [here](https://github.com/SINTEF-Geometry/SISL/blob/master/src/s1323.c#L176):

- `kstop==16`
- `kdimp2==5`

which means that the loop

~~~
  for (ki=0,kl=0 ; ki<kstop ; kl++,ki+=kdimp2)
    {
      temp = sdirec[kl];
      carray[ki] = (double)1.0 - temp*temp/tcost2;
    } 
~~~

iterates 4 times (0, 5, 10, 15) and `kl` takes the values 0, 1, 2, 3. 3 is out of bounds.

**Comment by VibekeSkytt** [comment]
You are right. The issue will be fixed.
