### ISSUE TITLE
Clarification of licensing

### ISSUE THREAD

**Issue by cbernardo** [SINTEF-Geometry/SISL#3]
1. On the SINTEF project page (http://www.sintef.no/projectweb/geometry-toolkits) it is stated that the library is available under the GPL for non-commercial use, but I can see no such statement in this git repository.

2. I would like to use the library to help support my project libIGES (https://github.com/cbernardo/libIGES) which I hope will eventually be included in the KiCad EDA package (http://www.kicad-pcb.org). Although KiCad is free software it is used by many companies for commercial purposes. Would the use of SISL in KiCad be a violation of the intention of the SINTEF licensing or would this be acceptable?

**Comment by tordokken** [comment]
Hi,

I see that you distribute under GNU GPL that does not allow commercial reselling of software but allows use. SISL was under GNU GPL and is now using to GNU Affero to avoid commercial cloud services being built on SISL without commercial licenses.

So our idea of licensing are quite similar, the software can be used by others but not linked into systems that are sold commercially. That will require a commercial license. We also restrict cloud servicers being built without a commercial license.

Thanks for point out that on our high level web-page info on the licenses are missing, however, they are as far as I know part of the download. WE have a major restruturing of the web and things move around. In addition we have move from our own serves for download to GIT-hub.

Tor Dokken

**Comment by cbernardo** [comment]
Thanks for your prompt response Tor.  I will make use of SISL but link it only if the user sets the correct build parameters; this way the user will have to be aware of SISL and the licensing before compiling and can make appropriate arrangements with SINTEF if they plan to use the code for cloud services.

Regards,
Cirilo
