### ISSUE TITLE
Failed to create closed surfaces :(

### ISSUE THREAD

**Issue by LorenzoVallisa** [SINTEF-Geometry/SISL#42]
No routine to construct closed surfaces + Using other routines fails when collapsing on a single point :(

**Comment by tordokken** [comment]
The are functionality in SISL that can be combined to construct closed surfaces. The functionality in SISL is based on requirements in BREP-CAD, where data structures of handling topology is outside of the math code. SISL can create rotational surfaces that are closed.  SISL was designed to address the need of BREP-CAD. In BREP CAD the parametrization at individual points is not assumed to be degenerate or collapse. Thus, this special situation was not in focus for the CAD-industries that originally funded SISL.
